server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password:
      root
    url: jdbc:postgresql://localhost:5432/reddit
    username:
      postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true